In [4]:
import numpy as np

In [5]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [6]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [8]:
a.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
a.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [10]:
a.reshape(12,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [11]:
a.reshape(3, -1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
a.reshape(6, -1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [14]:
a.reshape(-1, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [15]:
a.reshape(-1, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
a.reshape(12,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [17]:
a.ndim

1

In [18]:
a = np.random.randn(3, 4)
print(a)

[[-0.40032078 -0.8243476   1.64487483 -0.56630863]
 [-0.00802032  0.45755784  1.3611407   0.92294265]
 [-0.88840874 -0.97581313  0.31649286  0.02268385]]


In [19]:
b = a.flatten()
print(b)

[-0.40032078 -0.8243476   1.64487483 -0.56630863 -0.00802032  0.45755784
  1.3611407   0.92294265 -0.88840874 -0.97581313  0.31649286  0.02268385]


In [20]:
a.size == b.size

True

In [21]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [22]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


In [23]:
a.size == b.size

True

In [24]:
np.array_equal(a, b)

True

In [25]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
print('Массив a ', a, sep='\n')
print('Массив b ', b, sep='\n')

Массив a 
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Массив b 
[[1. 1.]
 [1. 1.]]


In [26]:
v = np.concatenate((a, b), axis = 0)
print(v)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


In [27]:
v.size

10

In [28]:
a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [29]:
A = a.reshape(3, 4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
At = A.transpose()
print(At)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [43]:
B = np.dot(A, At)
print(B)

[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


In [44]:
B.size

9

In [33]:
B_inv = np.linalg.inv(B)
print(B_inv)

[[-1.50443522e+14  3.00887044e+14 -1.50443522e+14]
 [ 3.00887044e+14 -6.01774088e+14  3.00887044e+14]
 [-1.50443522e+14  3.00887044e+14 -1.50443522e+14]]


In [34]:
np.linalg.det(B)

-2.1270440605979823e-12

In [35]:
np.random.seed(42)

In [36]:
a = np.arange(0, 16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [37]:
C = a.reshape(4, 4)
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [45]:
print(B)

[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


In [46]:
C.shape == B.shape

False

In [48]:
D = 10 * C + B
print(D)

ValueError: operands could not be broadcast together with shapes (4,4) (3,3) 